spring:  jpa:    properties:      javax:
        persistence:
          validation:
            mode: none  data:    web:      pageable:        default-page-size: 10
        max-page-size: 100  profiles:    active:    - dev
---
spring:  profiles: production
askify:  upload-path: storage-production
---
spring:  profiles: dev
askify:  upload-path: storage-dev